### ISSUE TITLE
Build arakoon-client.cmxs as well

### ISSUE THREAD

**Issue by vbmithr** [incubaid/arakoon#292]
This is needed by ocsigen for example, that loads modules at runtime.

**Comment by toolslive** [comment]
now you made me curious: what exactly are you trying to do ?

**Comment by vbmithr** [comment]
On 03/01/2014 13:41, Romain Slootmaekers wrote:

> now you have me curious: what exactly are you trying to do ?

An ocsipersist (http://ocsigen.org/ocsigenserver/api/Ocsipersist)
backend using Arakoon.

I am building a web application with Ocsigen where need a replicated
database (there is multiple machines in one network that serve the web
application and they need to be in sync all the time). I'm trying to use
Arakoon as an ocsipersist backend for that.

Cheers,

**Comment by toolslive** [comment]
I build arakoon_client.cmxs, and tried to load it via Dynlink, but that quickly cascades: 
it depends on 
lwt_unix.cmxs which depends on 
lwt-log.cmxs which depends on
lwt-syntax-log.cmxs which depends on
....

So are you sure providing arakoon_client.cmxs would do?

**Comment by vbmithr** [comment]
On 07/01/2014 14:23, Romain Slootmaekers wrote:

> I build arakoon_client.cmxs, and tried to load it via Dynlink, but that
> quickly cascades:
> it depends on
> lwt_unix.cmxs which depends on
> lwt-log.cmxs which depends on
> lwt-syntax-log.cmxs which depends on
> ....
> 
> So are you sure providing arakoon_client.cmxs would do?

A lot of libraries improperly build their cmxs. Typically, there is a
bug in the OASIS build system that cause cmxs to be produced from cmx
instead of cmxa which is usually what should be done. But you've done
your part here, then. It's not your concern if other libraries cannot be
loaded properly, I'll see what I can do here with the other involved
parties.

Thank you :)

**Comment by toolslive** [comment]
pull request: #298
